name: Deploy CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
#  schedule:
#      - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: yarn

      - name: Run build
        run: npm run build:cdn
        env:
          NODE_OPTIONS: '--max_old_space_size=4096 --openssl-legacy-provider'
          USE_LOG: false

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - uses: hocgin/action-qiniu-upload@master
        with:
          access_key: ${{ secrets.QINIU_ACCESS_KEY }}
          secret_key: ${{ secrets.QINIU_SECRET_KEY }}
          bucket: ${{ secrets.QINIU_BUCKET }}
          source_dir: 'dist'
          dest_dir: ${{github.event.repository.name}}
          ignore_source_map: true
          exclude: "index.html"
          overwrite: true
