name: Deploy CI

on:
  push:
    branches:
      - master
#  schedule:
#      - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Actions
      uses: actions/checkout@v2

    - name: Push
      uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: npm install && npm run build
